using HarmonyLib;
using RimWorld;
using System.Linq;
using Verse;

namespace GrimalkinRace
{
    // Remove autogenerated social/festival rituals for Grimalkin ideologies,
    [HarmonyPatch(typeof(IdeoFoundation), nameof(IdeoFoundation.AddSpecialPrecepts))]
    public static class Harmony_IdeoFoundation_AddSpecialPrecepts_RemoveAutogeneratedRituals
    {
        static void Postfix(ref IdeoFoundation __instance)
        {
            if (__instance.ideo.culture.IsGrimalkin())
            {
                // Remove social/festival rituals (identified by having a non-null instance count curve in their defs)
                __instance.ideo.precepts.RemoveAll(p => p is Precept_Ritual && p.def.preceptInstanceCountCurve != null);
            }
        }
    }

    // Prevent Ancients factions from using Grimalkin cultures
    [HarmonyPatch(typeof(IdeoFoundation), nameof(IdeoFoundation.RandomizeCulture))]
    public static class Harmony_IdeoFoundation_RandomizeCulture_HideGrimalkinCulturesFromCulturelessFactions
    {
        public static void Postfix(ref IdeoFoundation __instance, IdeoGenerationParms parms)
        {
            if (parms.forFaction.allowedCultures == null && __instance.ideo.culture.IsGrimalkin())
            {
                __instance.ideo.culture = DefDatabase<CultureDef>.AllDefsListForReading.Where(x => !x.defName.Contains("Grimalkin")).RandomElement();
            }
        }
    }

    // Disallow animal, weapon, and desired precepts for Mousekin ideologies
    [HarmonyPatch(typeof(IdeoFoundation), nameof(IdeoFoundation.RandomizePrecepts))]
    public static class Harmony_IdeoFoundation_RandomizePrecepts_NoVeneratedAnimalsAndNobleDespisedWeaponsForGrimalkin
    {
        public static void Postfix(ref IdeoFoundation __instance)
        {
            if (__instance.ideo.culture.IsGrimalkin())
            {
                __instance.ideo.precepts.RemoveAll(x => x.def == PreceptDefOf.AnimalVenerated || x.def == PreceptDefOf.NobleDespisedWeapons || x.def.preceptClass == typeof(Precept_Apparel));
            }
        }
    }

    // Remove autogenerated building and ritual seats for Grimalkin ideologies
    [HarmonyPatch(typeof(IdeoFoundation), nameof(IdeoFoundation.RandomizePrecepts))]
    public static class Harmony_IdeoFoundation_RandomizePrecepts_CleanUpBuildingPreceptsForGrimalkin
    {
        public static void Postfix(ref IdeoFoundation __instance, IdeoGenerationParms parms)
        {
            if (__instance.ideo.culture.IsGrimalkin())
            {
                __instance.ideo.precepts.RemoveAll(x => x is Precept_RitualSeat || x is Precept_Building building);
            }
        }
    }
}
